---
name: _loading
description: Load required parameters for the subsequent jobs

on:
  workflow_call:
    outputs:
      build_matrix:
        description: Build matrix
        value: ${{ jobs.loading.outputs.build_matrix }}

      full_matrix:
        description: Full Matrix containing lava description
        value: ${{ jobs.loading.outputs.full_matrix }}

      bootbins:
        description: Bootbins to generate Flat Build
        value: ${{ jobs.loading.outputs.bootbins }}

      ubuntu_matrix:
        description: Ubuntu matrix
        value: ${{ jobs.loading.outputs.ubuntu_matrix }}

jobs:
  loading:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.loading.outputs.build_matrix }}
      full_matrix: ${{ steps.loading.outputs.full_matrix }}
      bootbins: ${{ steps.loading.outputs.bootbins }}
      ubuntu_matrix: ${{ steps.loading.outputs.ubuntu_matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: qualcomm-linux/kernel-config

      - name: Load Parameters
        id: loading
        uses: qualcomm-linux/kernel-config/.github/actions/loading@main
