name: pre_merge
on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: string
        required: true
      sha:
        description: Head sha of the PR
        type: string
        required: true
      ref:
        description: Target branch
        type: string
        required: true
      repo:
        description: Target repository
        type: string
        required: true

jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}

  loading:
    needs: [init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/loading.yml@main
    secrets: inherit

  build:
    needs: [loading, init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/build.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      pr_number: ${{ inputs.pr }}
      branch: ${{ inputs.ref }}
      bootbins: ${{ needs.loading.outputs.bootbins }}

  check_run:
    runs-on: 
        self-hosted
    needs: build
    steps:
      - name: Create Check Run
        env:
          GH_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          HEAD_SHA=${{ inputs.sha }}
          s3_location="${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}"
          CHECK_RUN_ID=$(curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.repo }}/check-runs \
          -d '{"name":"Artifacts uploaded to S3","head_sha":"'"$HEAD_SHA"'","status":"in_progress","output":{"title":"Check S3 Location","summary":"","text":"'"$s3_location"'"}}' | jq -r '.id')

          curl -L -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.repo }}/check-runs/$CHECK_RUN_ID \
          -d '{"name":"Artifacts uploaded to S3","head_sha":"'"$HEAD_SHA"'","status":"completed","conclusion":"success","output":{"title":"Check S3 Location","summary":"","text":"'"$s3_location"'"}}'

  test:
    needs: [init-status, loading, build, check_run]
    uses: qualcomm-linux/kernel-config/.github/workflows/test.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}

  final-status:
    runs-on: ubuntu-latest
    needs: [init-status, loading, build, test]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: ${{ needs.test.result }}
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}
